spring:
  data:
    redis:
      host: ${REDIS_HOST:truthlens-redis}
      port: ${REDIS_PORT:6379}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

  threads:
    virtual:
      enabled: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

groq:
  api-url: "https://api.groq.com/openai/v1"
  api-key: ${GROQ_API_KEY:default-test-key}
  models:
    - "openai/gpt-oss-20b"
    - "llama-3.3-70b-versatile"
    - "qwen/qwen3-32b"