server:
  port: 8080

spring:
  codec:
    max-in-memory-size: 10MB
  data:
    redis:
      host: ${REDIS_HOST:truthlens-redis}
      port: ${REDIS_PORT:6379}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/truthlens}
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://truthlens-keycloak:8080/realms/truthlens/protocol/openid-connect/certs}

truthlens:
  gateway:
    cors:
      allowed-origins: "http://localhost:3000"
    rate-limit:
      replenish-rate: 5 
      burst-capacity: 10

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG
