version: '3.8'

services:

  config-server:
    build:
      context: ./config-server
    container_name: truthlens-config-server
    ports:
      - "8888:8888"
    volumes:
      - ./config-repo:/config-repo
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:///config-repo

  discovery-server:
    build:
      context: ./discovery-server
    container_name: truthlens-discovery-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server


  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: truthlens-keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://truthlens-postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # Start in dev mode for local testing
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
      KC_THEME_WELCOME_CACHE: "false"
      KC_THEME_CACHE: "false"
    command: start-dev --import-realm
    ports:
      - "8081:8080"
    volumes:
      - ./keycloak-theme/truthlens:/opt/keycloak/themes/truthlens
      - ./keycloak-config:/opt/keycloak/data/import
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: truthlens-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - keycloak-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: truthlens-backend
    restart: on-failure
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    extra_hosts:
      - "localhost:host-gateway"
    depends_on:
      - keycloak
      - postgres
      - config-server
      - discovery-server

  frontend:
    build:
      context: ./frontend
    container_name: truthlens-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
    environment:
      - AUTH_TRUST_HOST=true
      - AUTH_URL=http://localhost:3000
    extra_hosts:
      - "localhost:host-gateway"
    depends_on:
      - backend

volumes:
  keycloak-data:
    name: backend_keycloak-data
    external: true
